### ISSUE TITLE
Reading a very large log file gives OOM error

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/codesonar-plugin#27]
```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.io.BufferedReader.readLine(BufferedReader.java:356)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at org.apache.commons.io.IOUtils.readLines(IOUtils.java:1033)
	at org.jenkinsci.plugins.codesonar.CodeSonarPublisher.perform(CodeSonarPublisher.java:109)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1749)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
````

**Comment by buep** [comment]
When you fix this problem, can you please also search and review all the rest of the plugin code for where we load or read files, without taking into account those can be huge.

Search for read file, file etc.

**Comment by buep** [comment]
Use `grep -i -H -r "readFromFile" .` for example ... report findings on issues. You might want to check a lot of words other than `readFromFile`.

**Comment by MadsNielsen** [comment]
Right a couple of things. 

First off, it appears that the output we've been looking for doesn't even get produced in any of my cases, so the whole reading from the console log appears to be a wast of effort. 

Second, there are no other places where we use file handles or read from resources, so if we fix the issue on line 109 in CodeSonarPublisher.java we should be OK.

**Comment by buep** [comment]
> Second, there are no other places where we use file handles or read from resources,

Show the grep results...

**Comment by MadsNielsen** [comment]
Not doing it with grep, intellij "shift+f" -> "file" on root level folder is just as good. But anyways here are the results:

```
test/java/org/jenkinsci/plugins/codesonar/integration/conditions/ConditionIntegrationTestBase.java:        when(mockedAnalysisService.getAnalysisUrlFromLogFile(any(List.class)))
test/java/org/jenkinsci/plugins/codesonar/integration/CodeSonarPublisherIT.java:import org.apache.commons.io.FileUtils;
test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java:    public void providedLogFileWithAnAnalysisUrlPresent_shouldReturnAnAnalysisUrl() {
test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java:        final List<String> LOG_FILE_WITH_URL = new ArrayList<>();
test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java:        LOG_FILE_WITH_URL.add("codesonar: Files parsed successfully.  Logs are visible at:");
test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java:        LOG_FILE_WITH_URL.add("codesonar: http://10.10.1.125:8080/analysis/98.html");
test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java:        LOG_FILE_WITH_URL.add("Use 'codesonar analyze' to start the analysis");
test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java:        String result = analysisService.getAnalysisUrlFromLogFile(LOG_FILE_WITH_URL);
test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java:    public void providedLogFileWithNoAnalysisUrlPresent_shouldReturnNull() {
test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java:        final List<String> LOG_FILE_WITHOUT_URL = new ArrayList<>();
test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java:        LOG_FILE_WITHOUT_URL.add("codesonar: Files parsed successfully.  Logs are visible at:");
test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java:        LOG_FILE_WITHOUT_URL.add("Use 'codesonar analyze' to start the analysis");
test/java/org/jenkinsci/plugins/codesonar/unit/services/AnalysisServiceTest.java:        String result = analysisService.getAnalysisUrlFromLogFile(LOG_FILE_WITHOUT_URL);
main/resources/org/jenkinsci/plugins/codesonar/CodeSonarBuildAction/summary.jelly:    <t:summary icon="${it.getIconFileName()}">
Binary file main/webapp/icons/codesonar-logo.png matches
main/java/org/jenkinsci/plugins/codesonar/CodeSonarLatestAnalysisProjectAction.java:    public String getIconFileName() {
main/java/org/jenkinsci/plugins/codesonar/models/metrics/Metric.java:    private String file;
main/java/org/jenkinsci/plugins/codesonar/models/metrics/Metric.java:    public String getFile() {
main/java/org/jenkinsci/plugins/codesonar/models/metrics/Metric.java:        return file;
main/java/org/jenkinsci/plugins/codesonar/models/metrics/Metric.java:    public void setFile(String file) {
main/java/org/jenkinsci/plugins/codesonar/models/metrics/Metric.java:        this.file = file;
main/java/org/jenkinsci/plugins/codesonar/models/metrics/Metric.java:        return "Metric{" + "url=" + url + ", name=" + name + ", description=" + description + ", granularity=" + granularity + ", file=" + file + ", procedure=" + procedure + ", value=" + value + '}';
main/java/org/jenkinsci/plugins/codesonar/models/procedures/ProcedureRow.java:    private String file;
main/java/org/jenkinsci/plugins/codesonar/models/procedures/ProcedureRow.java:    public String getFile() {
main/java/org/jenkinsci/plugins/codesonar/models/procedures/ProcedureRow.java:        return file;
main/java/org/jenkinsci/plugins/codesonar/models/procedures/ProcedureRow.java:    public void setFile(String file) {
main/java/org/jenkinsci/plugins/codesonar/models/procedures/ProcedureRow.java:        this.file = file;
main/java/org/jenkinsci/plugins/codesonar/models/procedures/ProcedureRow.java:        hash = 23 * hash + Objects.hashCode(this.file);
main/java/org/jenkinsci/plugins/codesonar/models/procedures/ProcedureRow.java:        if (!Objects.equals(this.file, other.file)) {
main/java/org/jenkinsci/plugins/codesonar/models/procedures/ProcedureRow.java:        return "ProcedureRow{" + "file=" + file + ", procedure=" + procedure + ", metrics=" + metrics + '}';
main/java/org/jenkinsci/plugins/codesonar/models/analysis/Analysis.java:            if (message.contains("Bad File System")) {
main/java/org/jenkinsci/plugins/codesonar/models/analysis/Analysis.java:            } else if (message.contains("Bad Configuration File Setting")) {
main/java/org/jenkinsci/plugins/codesonar/models/analysis/Analysis.java:            } else if (message.contains("Bad Configuration File Settings")) {
main/java/org/jenkinsci/plugins/codesonar/models/analysis/Analysis.java:            } else if (message.contains("Missing Source File")) {
main/java/org/jenkinsci/plugins/codesonar/models/analysis/Analysis.java:            } else if (message.contains("Missing Source Files")) {
main/java/org/jenkinsci/plugins/codesonar/models/analysis/Warning.java:    private String file;
main/java/org/jenkinsci/plugins/codesonar/models/analysis/Warning.java:    public String getFile() {
main/java/org/jenkinsci/plugins/codesonar/models/analysis/Warning.java:        return file;
main/java/org/jenkinsci/plugins/codesonar/models/analysis/Warning.java:    public void setFile(String file) {
main/java/org/jenkinsci/plugins/codesonar/models/analysis/Warning.java:        this.file = file;
main/java/org/jenkinsci/plugins/codesonar/models/report/Column.java: * To change this template file, choose Tools | Templates
main/java/org/jenkinsci/plugins/codesonar/models/report/Text.java: * To change this template file, choose Tools | Templates
main/java/org/jenkinsci/plugins/codesonar/models/report/Title.java: * To change this template file, choose Tools | Templates
main/java/org/jenkinsci/plugins/codesonar/models/report/Row.java: * To change this template file, choose Tools | Templates
main/java/org/jenkinsci/plugins/codesonar/models/report/Report.java: * To change this template file, choose Tools | Templates
main/java/org/jenkinsci/plugins/codesonar/models/report/Table.java: * To change this template file, choose Tools | Templates
main/java/org/jenkinsci/plugins/codesonar/conditions/ConditionDescriptor.java: * To change this template file, choose Tools | Templates
main/java/org/jenkinsci/plugins/codesonar/CodeSonarProjectAction.java:    public String getIconFileName() {
main/java/org/jenkinsci/plugins/codesonar/CodeSonarPublisher.java:    public void perform(Run<?, ?> run, FilePath workspace, Launcher launcher, TaskListener listener) throws InterruptedException, IOException {
main/java/org/jenkinsci/plugins/codesonar/CodeSonarPublisher.java:        List<String> logFile = IOUtils.readLines(run.getLogReader());
main/java/org/jenkinsci/plugins/codesonar/CodeSonarPublisher.java:        String analysisUrl = analysisService.getAnalysisUrlFromLogFile(logFile);
main/java/org/jenkinsci/plugins/codesonar/CodeSonarBuildAction.java:    public String getIconFileName() {
main/java/org/jenkinsci/plugins/codesonar/services/IAnalysisService.java:    String getAnalysisUrlFromLogFile(List<String> logFile);
main/java/org/jenkinsci/plugins/codesonar/services/AnalysisService42.java:    public String getAnalysisUrlFromLogFile(List<String> logFile) {
main/java/org/jenkinsci/plugins/codesonar/services/AnalysisService42.java:        for (String line : logFile) {
main/java/org/jenkinsci/plugins/codesonar/services/AnalysisService40.java:    public String getAnalysisUrlFromLogFile(List<String> logFile) {
main/java/org/jenkinsci/plugins/codesonar/services/AnalysisService40.java:        for (String line : logFile) {
```

**Comment by buep** [comment]
Fine, I found these relevant for scrutiny and checking if they break with big files or inputs:


./src/main/java/org/jenkinsci/plugins/codesonar/CodeSonarPublisher.java:109:        List<String> logFile = IOUtils.readLines(run.getLogReader());
./src/main/java/org/jenkinsci/plugins/codesonar/CodeSonarPublisher.java:110:        String analysisUrl = analysisService.getAnalysisUrlFromLogFile(logFile);
./src/main/java/org/jenkinsci/plugins/codesonar/services/AnalysisService42.java:49:    public String getAnalysisUrlFromLogFile(List<String> logFile) {
./src/main/java/org/jenkinsci/plugins/codesonar/services/IAnalysisService.java:9:    String getAnalysisUrlFromLogFile(List<String> logFile);

But I guess that is also where you get the original error from.

**Comment by MadsNielsen** [comment]
Yep. I'm reading up on how you can process gigantic log files without using too much memory. I'll try to run some experiments with the logfile from AWS.

**Comment by buep** [comment]
But what about you said we didn't even need it? Isn't it old code that looks for the url in the console log, while we actually ask the user for it in the configuration?
So do we at all need to look for it?

**Comment by MadsNielsen** [comment]
@buep I'm worried about backwards compatibility. It seems to me that this might be with an older version of codesonar, so that removing it might cause older versions to fail. I initially just thought to delete it, but it might be dangerous.

**Comment by buep** [comment]
>  I'm worried about backwards compatibility. It seems to me that this might be with an older version of codesonar

As in plugin our code sonar hub? Not matter what we have the configuraiton in our plugin right?

I think we should ask Grammatech about the compatibility.

**Comment by MadsNielsen** [comment]
@buep I was being unclear, the code might be there to support older versions of Codesonar (the tool) than what we're testing with. But we can ask Grammatech about it.

**Comment by buep** [comment]
Yes, please ask before we do a lot of extra work handling large files for no reason.
